name: Build Tools
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build Tools
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
          id: go

      - name: Install Protobuf
        run:  |
          sudo apt update && sudo apt install -y protobuf-compiler libprotobuf-dev

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"
          echo "::add-path::$HOME/.pub-cache/bin"
          mkdir -p "${{ github.workspace }}"/go/{src,bin,pkg}

      - name: Build Tools for all (supported) platforms
        run:  |
          make this-flu-activate-plugin
          make this-tools-build-all

      - name: Get the current git tag
        id: get_current_git_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_current_git_tag.outputs.VERSION }}
          release_name: Release ${{ steps.get_current_git_tag.outputs.VERSION }}
          draft: true
          prerelease: false
          
      - name: Upload tools
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
          pattern: "tool/assets/*.zip"

